# completely stolen from: https://github.com/RamblingCookieMonster/PSDiskPart

version: 
  - ps: "$env:APPVEYOR_REPO_BRANCH."+$env:APPVEYOR_REPO_COMMIT.Substring(0,3)

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/

install:
  - cinst pester

test_script:
  - ps: powershell.exe -version 5.0 -executionpolicy bypass -noprofile -file .\Test\Appveyor.Pester.ps1 -Version 5
  - ps: powershell.exe -version 5.0 -executionpolicy bypass -noprofile -file .\Test\Appveyor.Pester.ps1 -Version 5 -Finalize