#
# Module manifest for module 'PSTrueCrypt'
#
# Generated by: Marc Kassay
#
# Generated on: 5/2/2017
#

@{
# Script module or binary module file associated with this manifest
RootModule = 'PSTrueCrypt.psm1'

# Version number of this module.
ModuleVersion = '0.0.8.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '48046c05-e3b6-41e0-bb42-4e88bbaa34c3'

# Author of this module
Author = 'Marc Kassay'

# Description of the functionality provided by this module
Description = 'PSTrueCrypt is a PowerShell module for mounting TrueCrypt and VeraCrypt containers.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'System.Windows.Forms.dll'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Mount-TrueCrypt',
    'Dismount-TrueCrypt',
    'Dismount-TrueCryptForceAll',
    'New-PSTrueCryptContainer',
    'Edit-PSTrueCryptContainer',
    'Remove-PSTrueCryptContainer',
    'Show-PSTrueCryptContainers',
    'Get-RegistrySubKeys',
    'Write-Container'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'mt',
    'dmt',
    'dmt*'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'en-US\PSTrueCrypt-help.xml',
    'resx\Error.resx',
    'resx\Information.resx',
    'resx\Verbose.resx',
    'resx\Warning.resx',
    'src\CIM\PSTrueCrypt.CIM.psm1',
    'src\Storage\Container.psm1',
    'src\Storage\PSTrueCrypt.Storage.psm1',
    'src\Utility\PSTrueCrypt.Utility.psm1',
    'src\Writer\Error.psm1',
    'src\Writer\Information.psm1',
    'src\Writer\PSTrueCrypt.Writer.psm1',
    'src\Writer\Verbose.psm1',
    'src\Writer\Warning.psm1',
    'src\PSTrueCrypt.CommandLine.psm1',
    'PSTrueCrypt.psd1',
    'PSTrueCrypt.psm1',
    'README.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('TrueCrypt', 'PowerShell', 'VeraCrypt', 'Mount', 'Encryption')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/marckassay/PSTrueCrypt/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/marckassay/PSTrueCrypt'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/marckassay/PSTrueCrypt/blob/master'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}
